name: Create and publish a Docker image

on:
  push:
  schedule:
    - cron: "17 17 * * *" # Run at 17:17 every day

env:
  REGISTRY: ghcr.io
  DOCKERFILE: Dockerfile
  IMAGE_TAG: kizzycode/thttpd:latest

jobs:
  build-and-push-image:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Login to Docker registry
        run: |
          docker login -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}" "${{ env.REGISTRY }}"
      
      - name: Build the Docker image
        run: |
          docker build . --file "${{ env.DOCKERFILE }}" --tag "${{ env.REGISTRY }}/${{ env.IMAGE_TAG }}"

      - name: Push the Docker image
        run: |
          docker push "${{ env.REGISTRY }}/${{ env.IMAGE_TAG }}"
      
